[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_def_mapping_enabled = 0
    let g:go_fmt_autosave = 1
    let g:go_highlight_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
'''

