[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_leader_key='<C-z>'
'''

[[plugins]]
repo = 'lepture/vim-jinja'
hook_add = '''
au BufNewFile,BufRead *.html,*.htm,*.shtml,*.stm set ft=jinja
'''
