[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = 'python'
hook_source = '''
let g:deoplete#sources#jedi#python_path = $HOME . '/.pyenv/shims/python'
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

