[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'morhetz/gruvbox.git'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#branch#enabled = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#wordcount#enabled = 0
    let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
    let g:airline#extensions#default#section_truncate_width = {}
    let g:airline#extensions#whitespace#enabled = 1
    let laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme = 'bubblegum'
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_def_mapping_enabled = 0
    let g:go_fmt_autosave = 1
    let g:go_highlight_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
'''


